using CodeCasa.AutoGenerated;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using CodeCasa.NetDaemon.Extensions.Observables;

namespace CodeCasa.CustomEntities.Automation.Sensors
{
    // todo: move to a common library
    public abstract class MotionSensor(
        IScheduler scheduler,
        BinarySensorEntity motionOccupancySensor,
        NumericSensorEntity motionIlluminanceLuxSensor)
    {
        public BinarySensorEntity MotionOccupancySensor { get; } = motionOccupancySensor;
        public NumericSensorEntity MotionIlluminanceLuxSensor { get; } = motionIlluminanceLuxSensor;

        public IObservable<bool> CreateMotionObservable(double brightnessThreshold = 5, TimeSpan? offDelay = null)
        {
            offDelay ??= TimeSpan.FromSeconds(25);

            var motionLastXTime =
                MotionOccupancySensor.PersistOnFor(offDelay.Value, scheduler);

            var brightnessLessThanX = MotionIlluminanceLuxSensor
                .ToBooleanObservable(s => s.State <= brightnessThreshold);

            var triggered = false;
            return motionLastXTime.CombineLatest(brightnessLessThanX, (motionTriggered, brightnessTriggered) =>
            {
                if (motionTriggered && brightnessTriggered)
                {
                    triggered = true;
                }
                else if (!motionTriggered)
                {
                    triggered = false;
                }

                return triggered;
            }).DistinctUntilChanged();
        }
    }
}
