using System.Reactive.Concurrency;
using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.Sensors.Composite;

namespace CodeCasa.CustomEntities.Automation.Sensors
{
    public class UpstairsHallwayAtticMotionSensor(
        IScheduler scheduler,
        BinarySensorEntities binarySensorEntities,
        SensorEntities sensorEntities)
        : MotionSensor(scheduler, binarySensorEntities.UpstairsHallwayAtticMotionSensorOccupancy,
            sensorEntities.UpstairsHallwayAtticMotionSensorIlluminance);
}
