using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.InputSelect;

public record DoorbellState : TypeSafeInputSelectEntity<DoorbellState.States>
{
    public DoorbellState(InputSelectEntities inputSelectEntities) 
        : base(inputSelectEntities.VariableDoorbellState)
    {
    }

    public enum States
    {
        Idle,
        Detection,
        Ringing
    }
}