using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.InputSelect;

public record LivingRoomWallPanelView : TypeSafeInputSelectEntity<LivingRoomWallPanelView.States>
{
    public LivingRoomWallPanelView(InputSelectEntities inputSelectEntities) 
        : base(inputSelectEntities.VariableLivingRoomWallPanelView)
    {
    }

    public enum States
    {
        Idle,
        Home,
        Doorbell
    }
}