using System.Reactive.Concurrency;
using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.Automations.Apps.Lights.Backyard.Observables;
using CodeCasa.Lights;
using NetDaemon.AppModel;

namespace CodeCasa.Automations.Apps.Lights.Backyard;

/// <summary>
/// One pipeline for the whole backyard. Each string light gets its own routine with a small offset, so they turn on
/// one by one; the wall lights follow ten seconds later with a slow fade. Energy saving turns everything off at night
/// once the shutters are closed.
/// </summary>
[NetDaemonApp]
internal class BackyardLightsApp
{
    public BackyardLightsApp(
        LightPipelineFactory lightPipelineFactory,
        LightEntities lightEntities,
        IScheduler scheduler)
    {
        lightPipelineFactory.SetupLightPipeline(lightEntities.BackyardLights, pipeline => pipeline
            .ForLight(lightEntities.BackyardPorchStringLights, light => light
                .When(new BackyardLightsRoutine(scheduler, TimeSpan.Zero), LightParameters.On()))
            .ForLight(lightEntities.BackyardPergolaStringLights, light => light
                .When(new BackyardLightsRoutine(scheduler, TimeSpan.FromSeconds(1)), LightParameters.On()))
            .ForLight(lightEntities.BackyardFenceStringLights, light => light
                .When(new BackyardLightsRoutine(scheduler, TimeSpan.FromSeconds(2)), LightParameters.On()))
            .ForLights([lightEntities.BackyardGarageLight, lightEntities.BackyardEntranceLight, lightEntities.BackyardDoorLight], lights => lights
                .When(new BackyardLightsRoutine(scheduler, TimeSpan.FromSeconds(10)), LightParameters.Relax.AsTransitionInSeconds(4)))
            .TurnOffWhen<BackyardLightsEnergySaving>());
    }
}
