using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.CustomEntities.Core.Extensions;
using CodeCasa.NetDaemon.RuntimeState.Extensions;

namespace CodeCasa.Dashboard.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection)
    {
        return serviceCollection
            .AddHomeAssistantGenerated()
            .AddNetDaemonRuntimeStateService()
            .AddCodeCasaCustomCoreEntities();
    }
}