using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.Extensions;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Notifications.Lights.Extensions;
using NetDaemon.AppModel;

namespace CodeCasa.Automations.Apps.Lights.LivingRoom;

/// <summary>
/// The living room wall switch toggles through scenes made in the Home Assistant scene editor.
/// The pipeline also shows light notifications, see <c>DoorbellLightNotifications</c>.
/// </summary>
[NetDaemonApp]
internal class LivingRoomLightsApp
{
    public LivingRoomLightsApp(
        LightPipelineFactory lightPipelineFactory,
        LightEntities lightEntities,
        SceneEntities sceneEntities,
        LivingRoomWallSwitch livingRoomWallSwitch)
    {
        lightPipelineFactory.SetupLightPipeline(lightEntities.LivingRoomLights, pipeline => pipeline
            .UseLightGroup(lightEntities.LivingRoomLightsZ2m)
            .AddInteractionNode(node => node
                .AddToggle(livingRoomWallSwitch,
                    sceneEntities.LivingRoomAmbiance,
                    sceneEntities.LivingRoomRelax,
                    sceneEntities.LivingRoomBright)
                .TurnOffWhenLastPersonToAsleepOrAway())
            .AddNotifications());
    }
}
