using CodeCasa.AutoGenerated;
using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.NetDaemon.Extensions.Observables;

namespace CodeCasa.Dashboard.ViewModels;

public class LightEntityVm
{
    private readonly LightEntity _lightEntity;
    private bool _isOn;

    public LightEntityVm (LightEntity lightEntity)
    {
        _lightEntity = lightEntity;

        _lightEntity.ToOnOffObservable().Subscribe(on => _isOn = on);
    }

    public bool IsOn
    {
        get => _isOn;
        set
        {
            if (value)
            {
                _lightEntity.TurnOn();
            }
            else
            {
                _lightEntity.TurnOff();
            }
            // Note: even though this value will also be updated by the light entity subscription, we update it here to make the UI responsive.
            // For now this implementation assumes the command is executed. In the future we might want to add a timer to be eventually correct.
            _isOn = value;
        }
    }
}