using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.TypedEntities;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;

namespace CodeCasa.CustomEntities.Core.Weather;

public record TypeSafeWeatherEntity : EnumEntity<WeatherTypes, TypeSafeWeatherEntity, EnumEntityState<WeatherTypes, WeatherAttributes>, WeatherAttributes>, IInputSelectEntityCore
{
    private static readonly Dictionary<WeatherTypes, string> WeatherTypeMap = new()
    {
        { WeatherTypes.ClearNight,    "clear-night" },
        { WeatherTypes.Cloudy,        "cloudy" },
        { WeatherTypes.Fog,           "fog" },
        { WeatherTypes.Hail,          "hail" },
        { WeatherTypes.Lightning,     "lightning" },
        { WeatherTypes.LightningRainy,"lightning-rainy" },
        { WeatherTypes.PartlyCloudy,  "partlycloudy" },
        { WeatherTypes.Pouring,       "pouring" },
        { WeatherTypes.Rainy,         "rainy" },
        { WeatherTypes.Snowy,         "snowy" },
        { WeatherTypes.SnowyRainy,    "snowy-rainy" },
        { WeatherTypes.Sunny,         "sunny" },
        { WeatherTypes.Windy,         "windy" },
        { WeatherTypes.WindyCloudy,   "windy-variant" },
        { WeatherTypes.Exceptional,   "exceptional" }
    };

    public TypeSafeWeatherEntity(IHaContext haContext, string entityId) : base(haContext, entityId, WeatherTypeMap)
    {
    }

    public TypeSafeWeatherEntity(IEntityCore entity) : base(entity, WeatherTypeMap)
    {
    }
}