using Microsoft.Extensions.DependencyInjection;

namespace CodeCasa.AutoGenerated.Extensions;

public static class GeneratedExtensions
{
    ///<summary>Registers all injectable generated types in the serviceCollection</summary>
    public static IServiceCollection AddHomeAssistantGenerated(this IServiceCollection serviceCollection)
    {
        return serviceCollection
            .AddTransient<Entities>()
            .AddTransient<AutomationEntities>()
            .AddTransient<BinarySensorEntities>()
            .AddTransient<CameraEntities>()
            .AddTransient<CoverEntities>()
            .AddTransient<InputSelectEntities>()
            .AddTransient<LightEntities>()
            .AddTransient<NotifyServices>()
            .AddTransient<PersonEntities>()
            .AddTransient<SensorEntities>()
            .AddTransient<SceneEntities>()
            .AddTransient<WeatherEntities>();
    }
}