using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.Doorbell
{
    public class FrontDoorDoorbell(CameraEntities cameraEntities) 
        : ReolinkDoorbell(cameraEntities.Doorbell, cameraEntities.FrontDoorFrontDoorDoorbellFluent);
}
