using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.Doorbell
{
    public class FrontDoorDoorbell(BinarySensorEntities binarySensorEntities) 
        : ReolinkDoorbell(binarySensorEntities.FrontDoorFrontDoorDoorbellPerson, binarySensorEntities.FrontDoorFrontDoorDoorbellVisitor);
}
