using System.Reactive.Linq;
using CodeCasa.AutoGenerated;
using NetDaemon.HassModel.Entities;

namespace CodeCasa.CustomEntities.Core.Doorbell;

public abstract class ReolinkDoorbell(CameraEntity cameraEntity, CameraEntity fluentCameraEntity)
{
    public IObservable<string> FluentUrl => cameraEntity.StateAllChangesWithCurrent()
        .Select(s => s.New?.Attributes?.AccessToken)
        .Where(at => !string.IsNullOrEmpty(at))
        .Select(at =>
        {
            var url = $"http://10.10.0.10:8123/api/camera_proxy_stream/camera.doorbell?token={at!}";
            return url;
        })
        .DistinctUntilChanged();
}