using CodeCasa.AutoGenerated;

namespace CodeCasa.CustomEntities.Core.Doorbell
{
    public abstract class ReolinkDoorbell(BinarySensorEntity personDetected, BinarySensorEntity bellPressed)
    {
        public BinarySensorEntity PersonDetected { get; } = personDetected;
        public BinarySensorEntity BellPressed { get; } = bellPressed;
    }
}
