using System.Reactive.Linq;
using CodeCasa.AutoGenerated;
using NetDaemon.HassModel.Entities;

namespace CodeCasa.CustomEntities.Core.Doorbell;

public abstract class ReolinkDoorbell
{
    private readonly CameraEntity _fluentCameraEntity;

    protected ReolinkDoorbell(CameraEntity cameraEntity, CameraEntity fluentCameraEntity)
    {
        _fluentCameraEntity = fluentCameraEntity;
    }
}