using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.Extensions;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using NetDaemon.AppModel;

namespace CodeCasa.Automations.Apps.Lights.Office;

/// <summary>
/// The office is controlled by a wall switch and a Hue dimmer switch: toggle, scene cycle and hold to dim.
/// All bulbs are addressed through their Zigbee group, so the whole room changes at once.
/// </summary>
[NetDaemonApp]
internal class OfficeLightsApp
{
    public OfficeLightsApp(
        LightPipelineFactory lightPipelineFactory,
        LightEntities lightEntities,
        OfficeWallSwitch officeWallSwitch,
        OfficeDimmerSwitch officeDimmerSwitch)
    {
        lightPipelineFactory.SetupLightPipeline(lightEntities.OfficeLights, pipeline => pipeline
            .UseLightGroup(lightEntities.OfficeLightsZ2m)
            .AddInteractionNode(node => node
                .AddToggle(officeWallSwitch, LightParameters.Bright)
                .AddToggle(officeDimmerSwitch.OnOffPressed, LightParameters.Bright)
                .AddCycle(officeDimmerSwitch.ScenePressed, LightParameters.Bright, LightParameters.Concentrate, LightParameters.Relax)
                .AddReactiveDimmer(officeDimmerSwitch)
                .TurnOffWhenLastPersonToAsleepOrAway()));
    }
}
