using CodeCasa.AutoGenerated.Extensions;
using CodeCasa.AutomationPipelines.Extensions;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.Mqtt.Extensions;
using CodeCasa.Automations.Apps.Lights.BackyardLights.Observables;
using CodeCasa.CustomEntities.Automation.Extensions;
using CodeCasa.Lights.NetDaemon.Scenes.Extensions;
using CodeCasa.Mqtt.Extensions;
using CodeCasa.Notifications.InputSelect.NetDaemon.Extensions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Occurify.Astro;

namespace CodeCasa.Automations.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCodeCasa(this IServiceCollection serviceCollection, IConfiguration configuration)
    {
        // Setting coordinates for the whole application to use.
        Coordinates.Local = new Coordinates(52.374191, 4.912269, 2.5);

        return serviceCollection
            .AddLightScenes()
            .AddAutomationPipelines()
            .AddHomeAssistantGenerated()
            .AddCodeCasaCustomAutomationEntities()
            .AddLightPipelines()
            .AddInputSelectNotifications(configuration)
            
            .AddTransient<BackyardLightsRoutineFactory>()
            .AddTransient<BackyardLightsEnergySaving>()

            .AddCodeCasaMqtt(configuration);
    }
}