using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.Mqtt;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.AutomationPipelines.Lights.Timeline;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.CustomEntities.Automation.Extensions;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using NetDaemon.AppModel;
using Occurify.Astro;
using Occurify.TimeZones;
using Occurify.Extensions;

namespace CodeCasa.Automations.Apps.Lights.Attic
{
    [NetDaemonApp]
    internal class AtticLightsApp
    {
        public AtticLightsApp(
            LightPipelineFactory lightPipelineFactory,
            LightEntities lightEntities,
            AtticWallSwitch atticWallSwitch,
            AtticDimmerSwitch atticDimmerSwitch,
            MqttPublisher mqttPublisher)
        {
            var slightlyBright = LightParameters.Bright with { Brightness = 153 };

            Action<ITimelineConfigurator> timelineConfig = tl => tl
                .Add(AstroInstants.LocalSunrises, LightParameters.Bright)
                .Add(AstroInstants.LocalSunsets.OffsetHours(-2), LightParameters.Bright)
                .Add(AstroInstants.LocalSunsets, LightParameters.Dimmed)
                .Add(TimeZoneInstants.DailyAt(5), LightParameters.Dimmed);

            lightPipelineFactory.SetupLightPipeline(lightEntities.AtticLights,
                pl => pl
                    .AddInteractionNode(i =>
                        i
                            .AddToggle(atticWallSwitch, timelineConfig)
                            .AddHueDimmerSwitch(atticDimmerSwitch, timelineConfig, slightlyBright,
                                LightParameters.Relax)
                            .TurnOffWhenLastPersonToAsleepOrAway()));
        }
    }
}
