using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.AutomationPipelines.Lights.Timeline;
using CodeCasa.CustomEntities.Automation.Extensions;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using CodeCasa.Notifications.Lights.Extensions;
using NetDaemon.AppModel;
using Occurify.Astro;
using Occurify.Extensions;
using Occurify.TimeZones;

namespace CodeCasa.Automations.Apps.Lights.Attic;

/// <summary>
/// The attic follows a natural light timeline: bright during the day, dimmed from sunset until early morning.
/// Both switches toggle that timeline; the scene button of the dimmer cycles through two fixed scenes.
/// </summary>
[NetDaemonApp]
internal class AtticLightsApp
{
    public AtticLightsApp(
        LightPipelineFactory lightPipelineFactory,
        LightEntities lightEntities,
        AtticWallSwitch atticWallSwitch,
        AtticDimmerSwitch atticDimmerSwitch)
    {
        var slightlyBright = LightParameters.Bright with { Brightness = 153 };

        Action<ITimelineConfigurator> naturalLight = tl => tl
            .Add(AstroInstants.LocalSunrises, LightParameters.Bright)
            .Add(AstroInstants.LocalSunsets.OffsetHours(-2), LightParameters.Bright)
            .Add(AstroInstants.LocalSunsets, LightParameters.Dimmed)
            .Add(TimeZoneInstants.DailyAt(5), LightParameters.Dimmed);

        lightPipelineFactory.SetupLightPipeline(lightEntities.AtticLights, pipeline => pipeline
            .UseLightGroup(lightEntities.AtticLightsZ2m)
            .AddInteractionNode(node => node
                .AddToggle(atticWallSwitch, naturalLight)
                .AddToggle(atticDimmerSwitch.OnOffPressed, naturalLight)
                .AddCycle(atticDimmerSwitch.ScenePressed, slightlyBright, LightParameters.Relax)
                .AddReactiveDimmer(atticDimmerSwitch)
                .TurnOffWhenLastPersonToAsleepOrAway())
            .AddNotifications());
    }
}
