using NetDaemon.AppModel;
using System.Text.Json;
using CodeCasa.AutoGenerated;
using CodeCasa.AutoGenerated.Extensions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MQTTnet;

namespace CodeCasa.Automations.Apps.LatencyTest
{
    [Focus]
    [NetDaemonApp]
    internal class LatencyTest : IAsyncDisposable
    {
        private readonly LightEntities _lightEntities;
        private readonly IConfiguration _configuration;
        private readonly ILogger<LatencyTest> _logger;
        private readonly IMqttClient _mqttClient;
        private readonly string _deviceCommandTopic = "zigbee2mqtt/Attic Spot Middle Door/set";

        // FLOOD CONFIGURATION: High resolution + low delay creates a massive bottleneck
        private const int CommandDelayMs = 30;

        public LatencyTest(
            LightEntities lightEntities,
            IConfiguration configuration,
            ILogger<LatencyTest> logger)
        {
            _lightEntities = lightEntities;
            _configuration = configuration;
            _logger = logger;

            var factory = new MqttClientFactory();
            _mqttClient = factory.CreateMqttClient();

            _ = Task.Run(async () =>
            {
                try
                {
                    await InitializeMqttClientAsync();
                    await RunTestAsync();
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Test failed");
                    Console.WriteLine($"ERROR: Test failed - {ex.Message}");
                }
            });
        }

        private async Task InitializeMqttClientAsync()
        {
            var mqttHost = _configuration.GetValue<string>("MQTT:Host") ?? "localhost";
            var mqttPort = _configuration.GetValue<int>("MQTT:Port", 1883);
            var mqttUser = _configuration.GetValue<string>("MQTT:Username");
            var mqttPassword = _configuration.GetValue<string>("MQTT:Password");

            var options = new MqttClientOptionsBuilder()
                .WithTcpServer(mqttHost, mqttPort)
                .WithClientId($"LatencyTest_{Guid.NewGuid()}")
                .WithCleanSession();

            if (!string.IsNullOrEmpty(mqttUser))
            {
                options.WithCredentials(mqttUser, mqttPassword);
            }

            await _mqttClient.ConnectAsync(options.Build(), CancellationToken.None);
            Console.WriteLine($"Connected to MQTT broker at {mqttHost}:{mqttPort}");
        }

        private async Task RunTestAsync()
        {
            Console.WriteLine("\n" + new string('=', 80));
            Console.WriteLine("AGGRESSIVE RUBBER-BANDING TEST");
            Console.WriteLine(new string('=', 80) + "\n");

            var sequence = CreateHighResolutionSequence();

            // Reset light
            _lightEntities.AtticSpotMiddleDoor.TurnOff();
            await Task.Delay(2000);

            // 1. Direct MQTT Path
            Console.WriteLine($"Running Direct MQTT Path ({sequence.Length} commands)...");
            var mqttStart = DateTime.UtcNow;
            await SendMqttCommandsAsync(sequence);
            var mqttDuration = DateTime.UtcNow - mqttStart;
            Console.WriteLine($">> Code finished MQTT loop in: {mqttDuration.TotalSeconds:F2}s");

            // Give the mesh time to settle
            await Task.Delay(20000);
            _lightEntities.AtticSpotMiddleDoor.TurnOff();
            await Task.Delay(2000);

            // 2. NetDaemon Path
            Console.WriteLine($"\nRunning NetDaemon Path ({sequence.Length} commands)...");
            var ndStart = DateTime.UtcNow;
            await SendNetDaemonCommandsAsync(sequence);
            var ndDuration = DateTime.UtcNow - ndStart;
            Console.WriteLine($">> Code finished NetDaemon loop in: {ndDuration.TotalSeconds:F2}s");
            Console.WriteLine(">> WATCH THE BULB NOW: It will keep dimming after the console stops!");
            _lightEntities.AtticSpotMiddleDoor.TurnOff();
            Console.WriteLine("\n" + new string('=', 80));
            Console.WriteLine("TEST COMPLETE");
            Console.WriteLine(new string('=', 80) + "\n");
        }

        private async Task SendMqttCommandsAsync(int[] sequence)
        {
            for (int i = 0; i < sequence.Length; i++)
            {
                var brightness = sequence[i];
                var payload = JsonSerializer.Serialize(new { state = "ON", brightness, transition = 0 });
                await _mqttClient.PublishStringAsync(_deviceCommandTopic, payload);

                await Task.Delay(CommandDelayMs);
            }
        }

        private async Task SendNetDaemonCommandsAsync(int[] sequence)
        {
            for (int i = 0; i < sequence.Length; i++)
            {
                var brightness = sequence[i];

                // Explicitly enforcing transition 0 so we only isolate API/bus queue latency
                _lightEntities.AtticSpotMiddleDoor.TurnOn(brightness: brightness, transition: 0);

                await Task.Delay(CommandDelayMs);
            }
        }

        private static int[] CreateHighResolutionSequence()
        {
            var sequence = new List<int>();

            // Linear ramp up (steps of 4 to keep total loop around ~4 seconds)
            for (int i = 5; i <= 255; i += 4) sequence.Add(i);
            // Linear ramp down
            for (int i = 255; i >= 5; i -= 4) sequence.Add(i);
            // Linear ramp up again
            for (int i = 5; i <= 255; i += 4) sequence.Add(i);

            return sequence.ToArray();
        }

        public async ValueTask DisposeAsync()
        {
            if (_mqttClient.IsConnected)
            {
                await _mqttClient.DisconnectAsync();
            }
            _mqttClient?.Dispose();
        }
    }
}