using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.People;
using CodeCasa.CustomEntities.Automation.Sensors;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using CodeCasa.Lights.NetDaemon.Extensions;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.AppModel;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Reactive.Boolean;
using System.Reactive.Concurrency;
using System.Reactive.Linq;

namespace CodeCasa.Automations.Apps.Lights.BathroomLights
{
    [Focus]
    [NetDaemonApp]
    internal class BathroomLightsApp
    {
        public BathroomLightsApp(
            LightPipelineFactory lightPipelineFactory,
            LightEntities lightEntities,
            BathroomMotionSensor bathroomMotionSensor,
            BathroomWallSwitch bathroomWallSwitch,
            PeopleEntities people,
            IScheduler scheduler)
        {
            var motionDetected = bathroomMotionSensor.Motion.Where(occupied => occupied);
            var pipeline = lightPipelineFactory.CreateLightPipeline(lightEntities.BathroomSpotWindow.AsLight(), b =>
            {
                b
                    .EnableLogging()
                    .AddPipelineWhen<BathroomMotionSensor>(pc =>
                    {
                        pc.When(people.AnyAsleepWithCurrent(), LightParameters.Bright with { Brightness = 30 })
                            .When<BathroomLightTimelineNode>(people.AnyAsleepWithCurrent().Not());
                    })
                    .AddPipeline(pc =>
                    {
                        pc.When(people.AnyAsleepWithCurrent(), LightParameters.Bright with { Brightness = 30 })
                            .When<BathroomLightTimelineNode>(people.AnyAsleepWithCurrent().Not());
                    })
                    .AddReactiveNode(c =>
                    {
                        c.AddToggle(bathroomWallSwitch,
                            sp => new BathroomLightTimelineNode(sp.GetRequiredService<IScheduler>()).TurnOffAfter(TimeSpan.FromMinutes(15), motionDetected, sp.GetRequiredService<IScheduler>()),
                            context => context.CreateAutoOffLightNode(LightParameters.Relax, TimeSpan.FromMinutes(15), motionDetected),
                            context => context.CreateAutoOffLightNode(LightParameters.NightLight, TimeSpan.FromMinutes(15), motionDetected));
                    });
            });

            var settings = new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                ContractResolver = new IgnoreObservablesContractResolver(),
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            string jsonString = JsonConvert.SerializeObject(pipeline, settings);

            bathroomMotionSensor.Subscribe(x =>
            {
                Console.WriteLine("Test");
            });
        }

        private class IgnoreObservablesContractResolver : DefaultContractResolver
        {
            protected override JsonProperty CreateProperty(System.Reflection.MemberInfo member, MemberSerialization memberSerialization)
            {
                var property = base.CreateProperty(member, memberSerialization);

                if (property.PropertyType is not null &&
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(IObservable<>))
                {
                    property.ShouldSerialize = _ => false;
                }

                return property;
            }
        }
    }
}
