using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.People;
using CodeCasa.CustomEntities.Automation.Sensors;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using CodeCasa.Lights.NetDaemon.Extensions;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.AppModel;
using Reactive.Boolean;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using CodeCasa.Mqtt;
using CodeCasa.Mqtt.Extensions;

namespace CodeCasa.Automations.Apps.Lights.BathroomLights
{
    [Focus]
    [NetDaemonApp]
    internal class BathroomLightsApp
    {
        public BathroomLightsApp(
            LightPipelineFactory lightPipelineFactory,
            LightEntities lightEntities,
            BathroomMotionSensor bathroomMotionSensor,
            BathroomWallSwitch bathroomWallSwitch,
            PeopleEntities people,
            IScheduler scheduler,
            MqttPublisher mqttPublisher)
        {
            var motionDetected = bathroomMotionSensor.Motion.Where(occupied => occupied);
            lightPipelineFactory.CreateLightPipeline(lightEntities.BathroomSpotWindow.AsLight(), b =>
            {
                b
                    .PublishTelemetryToMqtt(mqttPublisher)
                    .EnableLogging()
                    .AddPipelineWhen<BathroomMotionSensor>(pc =>
                    {
                        pc.When(people.AnyAsleepWithCurrent(), LightParameters.Bright with { Brightness = 30 })
                            .When<BathroomLightTimelineNode>(people.AnyAsleepWithCurrent().Not());
                    })
                    .AddPipeline(pc =>
                    {
                        pc.When(people.AnyAsleepWithCurrent(), LightParameters.Bright with { Brightness = 30 })
                            .When<BathroomLightTimelineNode>(people.AnyAsleepWithCurrent().Not());
                    })
                    .AddReactiveNode(c =>
                    {
                        c.AddToggle(bathroomWallSwitch,
                            sp => new BathroomLightTimelineNode(sp.GetRequiredService<IScheduler>()).TurnOffAfter(TimeSpan.FromMinutes(15), motionDetected, sp.GetRequiredService<IScheduler>()),
                            context => context.CreateAutoOffLightNode(LightParameters.Relax, TimeSpan.FromMinutes(15), motionDetected),
                            context => context.CreateAutoOffLightNode(LightParameters.NightLight, TimeSpan.FromMinutes(15), motionDetected));
                    });
            });
        }
    }
}
