using System.Reactive.Concurrency;
using CodeCasa.AutoGenerated;
using CodeCasa.NetDaemon.Extensions.Observables;
using Occurify;
using Occurify.Reactive.Extensions;
using Occurify.TimeZones;
using Reactive.Boolean;

namespace CodeCasa.Automations.Apps.Lights.BackyardLights.Observables;

public class BackyardLightsEnergySaving : IObservable<bool>
{
    private readonly IObservable<bool> _observable;

    public BackyardLightsEnergySaving(CoverEntities coverEntities, IScheduler scheduler)
    {
        var timeWindow = PeriodTimeline.Between(TimeZoneInstants.DailyAt(23), TimeZoneInstants.DailyAt(6)).ToBooleanObservable(scheduler);

        var livingRoomCurtainsClosed = coverEntities.LivingRoomBackWindowCurtain.ToOpenClosedObservable().Not();
        var livingRoomRollerShutterClosed = coverEntities.LivingRoomRollerShutter.ToOpenClosedObservable().Not();
        var anyLivingRoomShutterClosed = livingRoomCurtainsClosed.Or(livingRoomRollerShutterClosed);

        var kitchenRollerShutterClosed = coverEntities.KitchenRollerShutter.ToOpenClosedObservable().Not();

        _observable = timeWindow
            .And(anyLivingRoomShutterClosed)
            .And(kitchenRollerShutterClosed);
    }

    public IDisposable Subscribe(IObserver<bool> observer)
    {
        return _observable.Subscribe(observer);
    }
}