using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.Automations.Apps.Lights.BackyardLights.Observables;
using CodeCasa.Lights;
using CodeCasa.Notifications.Lights;
using CodeCasa.Notifications.Lights.Extensions;
using NetDaemon.AppModel;

namespace CodeCasa.Automations.Apps.Lights.BackyardLights;

[NetDaemonApp]
internal class BackyardLightsApp
{
    public BackyardLightsApp(
        LightPipelineFactory pipelineFactory,
        LightEntities lightEntities,
        LightNotificationManagerContext lightNotificationManager,
        BackyardLightsRoutineFactory backyardLightsRoutineFactory)
    {
        // We use a separate pipeline for each light string to allow for different timing on the startup routine.
        // This results in a nice animation, in which lights are turned on one by one.
        var stringLights = new[]
        {
            lightEntities.BackyardPorchStringLights, 
            lightEntities.BackyardPergolaStringLights,
            lightEntities.BackyardFenceStringLights
        };
        for (var i = 0; i < stringLights.Length; i++)
        {
            var light = stringLights[i];
            var index = i;
            pipelineFactory
                .SetupLightPipeline(light, b =>
                {
                    b
                        .TurnOnWhen(backyardLightsRoutineFactory.Create(TimeSpan.FromSeconds(index)))
                        .TurnOffWhen<BackyardLightsEnergySaving>()
                        .AddNotifications(lightNotificationManager);
                });
        }

        // All other lights should turn on slowly at the same time.
        // Note: We could actually use a single pipeline for this. But as we generate parameters based on light entity, I split them up. This way, even if the light type changes, this implementation will still work.
        const int transitionSeconds = 4;
        const int offsetSeconds = 10;
        var wallLights = new[]
        {
            lightEntities.BackyardGarageLight,
            lightEntities.BackyardEntranceLight,
            lightEntities.BackyardDoorLight
        };
        foreach (var light in wallLights)
        {
            pipelineFactory
                .SetupLightPipeline(light, builder =>
                {
                    builder
                        .When(backyardLightsRoutineFactory.Create(offsetSeconds), LightParameters.Relax.AsTransitionInSeconds(transitionSeconds))
                        .TurnOffWhen<BackyardLightsEnergySaving>()
                        .AddNotifications(lightNotificationManager);
                });
        }
    }
}