using CodeCasa.AutoGenerated;
using CodeCasa.CustomEntities.Core.Doorbell;
using CodeCasa.CustomEntities.Core.Events;
using CodeCasa.CustomEntities.Core.GoogleHome;
using CodeCasa.CustomEntities.Core.InputSelect;
using NetDaemon.AppModel;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using System.Text.Json.Serialization;
using CodeCasa.NetDaemon.Extensions.Observables;
using CodeCasa.NetDaemon.Utilities.Extensions;
using Reactive.Boolean;

namespace CodeCasa.Automations.Apps.Dashboard
{
    [NetDaemonApp]
    internal class LivingRoomPanelNavigation
    {
        private readonly IHaContext _context;
        private readonly AutomationEntities _automationEntities;
        private readonly InputSelectEntities _inputSelectEntities;
        private readonly GoogleHomeAlarmEntities _googleHomeAlarmEntities;
        private readonly GoogleHomeTimerEntities _googleHomeTimerEntities;
        private readonly LivingRoomWallPanelView _livingRoomWallPanelView;
        private readonly FrontDoorDoorbell _frontDoorDoorbell;
        private readonly IScheduler _scheduler;
        private bool _hasInfoToDisplay;
        private DateTime _currentStateActivated = DateTime.MinValue;
        private IDisposable? _scheduleDisposable;

        public LivingRoomPanelNavigation(
            IHaContext context,
            AutomationEntities automationEntities,
            InputSelectEntities inputSelectEntities,
            GoogleHomeAlarmEntities googleHomeAlarmEntities,
            GoogleHomeTimerEntities googleHomeTimerEntities,
            LivingRoomWallPanelView livingRoomWallPanelView,
            FrontDoorDoorbell frontDoorDoorbell,
            IScheduler scheduler)
        {
            _context = context;
            _automationEntities = automationEntities;
            _inputSelectEntities = inputSelectEntities;
            _googleHomeAlarmEntities = googleHomeAlarmEntities;
            _googleHomeTimerEntities = googleHomeTimerEntities;
            _livingRoomWallPanelView = livingRoomWallPanelView;
            _frontDoorDoorbell = frontDoorDoorbell;
            _scheduler = scheduler;

            livingRoomWallPanelView.StateChangesWithCurrent().Subscribe(_ =>
            {
                DetermineDesiredStateAndActivateWhenAppropriate();
            });

            SubscribeToProximity();
            SubscribeToInfo();
            SubscribeToDoorbell();
        }

        private LivingRoomWallPanelView.States DetermineDesiredState()
        {
            if (_frontDoorDoorbell.BellPressed.IsOn() || _frontDoorDoorbell.PersonDetected.IsOn())
            {
                return LivingRoomWallPanelView.States.Doorbell;
            }

            if (_hasInfoToDisplay)
            {
                return LivingRoomWallPanelView.States.Home;
            }

            return LivingRoomWallPanelView.States.Idle;
        }

        private void DetermineDesiredStateAndActivateWhenAppropriate()
        {
            var desiredState = DetermineDesiredState();
            if (_livingRoomWallPanelView.State == desiredState)
            {
                return;
            }
            if (desiredState == LivingRoomWallPanelView.States.Doorbell)
            {
                ActivateStateAfterMinimumTimeHasPassed(LivingRoomWallPanelView.States.Doorbell, TimeSpan.Zero);
                // Should not occur, but just in case to prevent overheating.
                ActivateStateAfterMinimumTimeHasPassed(LivingRoomWallPanelView.States.Idle, TimeSpan.FromMinutes(5));
                return;
            }
            if (desiredState == LivingRoomWallPanelView.States.Home)
            {
                if (_livingRoomWallPanelView.State == LivingRoomWallPanelView.States.Idle)
                {
                    ActivateStateAfterMinimumTimeHasPassed(desiredState, TimeSpan.FromSeconds(3));
                    return;
                }
            }
            ActivateStateAfterMinimumTimeHasPassed(desiredState, TimeSpan.FromSeconds(20));
        }

        private void ActivateStateAfterMinimumTimeHasPassed(LivingRoomWallPanelView.States desiredState,
            TimeSpan minimumTime)
        {
            _scheduleDisposable?.Dispose();
            _scheduleDisposable = null;
            if (DateTime.UtcNow - _currentStateActivated < minimumTime)
            {
                _scheduleDisposable = _scheduler.Schedule(minimumTime - (DateTime.UtcNow - _currentStateActivated), () =>
                {
                    _currentStateActivated = DateTime.UtcNow;
                    _livingRoomWallPanelView.SelectOption(desiredState);
                });
                return;
            }
            _currentStateActivated = DateTime.UtcNow;
            _livingRoomWallPanelView.SelectOption(desiredState);
        }

        private void SubscribeToProximity()
        {
            _context.Events
                .Filter<AutomationTriggeredEventData>(Events.AutomationTriggeredEvent)
                .Where(e => e.Data?.EntityId == _automationEntities.WebhookLivingRoomWallPanelProximityDetected.EntityId)
                .Select(_ => true)
                .Subscribe(_ =>
                {
                    if (_livingRoomWallPanelView.State == LivingRoomWallPanelView.States.Idle)
                    {
                        ActivateStateAfterMinimumTimeHasPassed(LivingRoomWallPanelView.States.Home, TimeSpan.Zero);
                    }
                });
        }

        private void SubscribeToInfo()
        {
            var notificationCount =
                _inputSelectEntities.LivingRoomPanelNotifications.StateAllChangesWithCurrent().Select(s =>
                    string.IsNullOrEmpty(s.New?.Attributes?.Options?.FirstOrDefault())
                        ? 0
                        : s.New.Attributes.Options.Count);
            var alarmCount = _googleHomeAlarmEntities.Select(gt => gt
                    .StateAllChangesDeserialized<SpeakerAlarmInfo>())
                .CombineLatest()
                .Select(speakerInfos => speakerInfos.Sum(s => s.Alarms?.Count ?? 0));
            var timerCount = _googleHomeTimerEntities.Select(gt => gt
                    .StateAllChangesDeserialized<SpeakerTimerInfo>())
                .CombineLatest()
                .Select(speakerInfos => speakerInfos.Sum(s => s.Timers?.Count ?? 0));
            var infoCount = notificationCount.CombineLatest(alarmCount, timerCount, (c1, c2, c3) => c1 + c2 + c3);

            infoCount.Subscribe(c => _hasInfoToDisplay = c > 0);
            infoCount
                .Scan(
                    (prev: 0, curr: 0),
                    (state, newCount) => (prev: state.curr, curr: newCount)
                )
                .Select(state =>
                {
                    if (state.curr == 0) return false;
                    if (state.curr > state.prev) return true;
                    return (bool?)null;
                })
                .Where(b => b != null).Subscribe(_ => DetermineDesiredStateAndActivateWhenAppropriate());
        }

        private void SubscribeToDoorbell()
        {
            var personDetected = _frontDoorDoorbell.PersonDetected.ToBooleanObservable();
            var bellPressed = _frontDoorDoorbell.BellPressed.ToBooleanObservable();
            bellPressed.Or(personDetected).Subscribe(_ => DetermineDesiredStateAndActivateWhenAppropriate());
        }

        // ReSharper disable once ClassNeverInstantiated.Local
        private record AutomationTriggeredEventData
        {
            [JsonPropertyName("entity_id")] public string? EntityId { get; init; }
        }
    }
}
