using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class BinarySensorEntities
{
    private readonly IHaContext _haContext;

    public BinarySensorEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all binary_sensor entities currently registered (at runtime) in Home Assistant as BinarySensorEntity</summary>
    public IEnumerable<BinarySensorEntity> EnumerateAll() => _haContext.GetAllEntities()
        .Where(e => e.EntityId.StartsWith("binary_sensor.")).Select(e => new BinarySensorEntity(e));

    ///<summary>Bathroom Motion Sensor Occupancy</summary>
    public BinarySensorEntity BathroomMotionSensorOccupancy => new(_haContext, "binary_sensor.bathroom_motion_sensor_occupancy");
    ///<summary>Front Door Doorbell Person</summary>
    public BinarySensorEntity FrontDoorFrontDoorDoorbellPerson => new(_haContext, "binary_sensor.front_door_front_door_doorbell_person");
    ///<summary>Front Door Doorbell Visitor</summary>
    public BinarySensorEntity FrontDoorFrontDoorDoorbellVisitor => new(_haContext, "binary_sensor.front_door_front_door_doorbell_visitor");
    ///<summary>Office Motion Sensor Occupancy</summary>
    public BinarySensorEntity OfficeMotionSensorOccupancy => new(_haContext, "binary_sensor.office_motion_sensor_occupancy");
    ///<summary>Upstairs Hallway Attic Motion Sensor Occupancy</summary>
    public BinarySensorEntity UpstairsHallwayAtticMotionSensorOccupancy => new(_haContext, "binary_sensor.upstairs_hallway_attic_motion_sensor_occupancy");
}