using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class InputSelectEntities
{
    private readonly IHaContext _haContext;
    public InputSelectEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all input_select entities currently registered (at runtime) in Home Assistant as InputSelectEntity</summary>
    public IEnumerable<InputSelectEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("input_select.")).Select(e => new InputSelectEntity(e));

    ///<summary>Jane Notifications</summary>
    public InputSelectEntity JaneNotifications => new(_haContext, "input_select.jane_notifications");
    ///<summary>Jane State</summary>
    public InputSelectEntity JaneDoeState => new(_haContext, "input_select.jane_state");
    ///<summary>Jasper Notifications</summary>
    public InputSelectEntity JasperNotifications => new(_haContext, "input_select.jasper_notifications");
    ///<summary>Jasper State</summary>
    public InputSelectEntity JasperState => new(_haContext, "input_select.jasper_state");
    ///<summary>Living Room Panel Notifications</summary>
    public InputSelectEntity LivingRoomPanelNotifications => new(_haContext, "input_select.living_room_panel_notifications");
    ///<summary>Variable Doorbell State</summary>
    public InputSelectEntity VariableDoorbellState => new(_haContext, "input_select.variable_doorbell_state");
    ///<summary>Variable Living Room Wall Panel View</summary>
    public InputSelectEntity VariableLivingRoomWallPanelView => new(_haContext, "input_select.variable_living_room_wall_panel_view");
}