using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using System.Text.Json.Serialization;

namespace CodeCasa.AutoGenerated;

public partial class InputSelectEntities
{
    private readonly IHaContext _haContext;
    public InputSelectEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all input_select entities currently registered (at runtime) in Home Assistant as InputSelectEntity</summary>
    public IEnumerable<InputSelectEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("input_select.")).Select(e => new InputSelectEntity(e));

    ///<summary>Jane Notifications</summary>
    public InputSelectEntity JaneNotifications => new(_haContext, "input_select.jane_notifications");
    ///<summary>Jane State</summary>
    public InputSelectEntity JaneDoeState => new(_haContext, "input_select.jane_state");
    ///<summary>Jasper Notifications</summary>
    public InputSelectEntity JasperNotifications => new(_haContext, "input_select.jasper_notifications");
    ///<summary>Jasper State</summary>
    public InputSelectEntity JasperState => new(_haContext, "input_select.jasper_state");
    ///<summary>Living Room Panel Notifications</summary>
    public InputSelectEntity LivingRoomPanelNotifications => new(_haContext, "input_select.living_room_panel_notifications");
    ///<summary>Variable Doorbell State</summary>
    public InputSelectEntity VariableDoorbellState => new(_haContext, "input_select.variable_doorbell_state");
    ///<summary>Variable Living Room Wall Panel View</summary>
    public InputSelectEntity VariableLivingRoomWallPanelView => new(_haContext, "input_select.variable_living_room_wall_panel_view");
}

public partial record CameraEntity : Entity<CameraEntity, EntityState<CameraAttributes>, CameraAttributes>, ICameraEntityCore
{
    public CameraEntity(IHaContext haContext, string entityId) : base(haContext, entityId)
    {
    }

    public CameraEntity(IEntityCore entity) : base(entity)
    {
    }
}

public partial record CameraAttributes
{
    [JsonPropertyName("device_class")]
    public string? DeviceClass { get; init; }

    [JsonPropertyName("entity_picture")]
    public string? EntityPicture { get; init; }

    [JsonPropertyName("friendly_name")]
    public string? FriendlyName { get; init; }

    [JsonPropertyName("supported_features")]
    public double? SupportedFeatures { get; init; }

    [JsonPropertyName("access_token")]
    public string? AccessToken { get; init; }

    [JsonPropertyName("motion_detection")]
    public bool? MotionDetection { get; init; }

    [JsonPropertyName("client_id")]
    public string? ClientId { get; init; }

    [JsonPropertyName("camera_name")]
    public string? CameraName { get; init; }
}

public partial class CameraEntities
{
    private readonly IHaContext _haContext;
    public CameraEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all camera entities currently registered (at runtime) in Home Assistant as CameraEntity</summary>
    public IEnumerable<CameraEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("camera.")).Select(e => new CameraEntity(e));
    ///<summary>Doorbell</summary>
    public CameraEntity Doorbell => new(_haContext, "camera.doorbell");
    ///<summary>Front Door Doorbell Fluent</summary>
    public CameraEntity FrontDoorFrontDoorDoorbellFluent => new(_haContext, "camera.front_door_front_door_doorbell_fluent");
}