using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class LightEntities
{
    private readonly IHaContext _haContext;
    public LightEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all light entities currently registered (at runtime) in Home Assistant as LightEntity</summary>
    public IEnumerable<LightEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("light.")).Select(e => new LightEntity(e));
    ///<summary>Attic Lights</summary>
    public LightEntity AtticLights => new(_haContext, "light.attic_lights");
    ///<summary>attic_lights_z2m</summary>
    public LightEntity AtticLightsZ2m => new(_haContext, "light.attic_lights_z2m");
    ///<summary>Attic Spot Middle Door</summary>
    public LightEntity AtticSpotMiddleDoor => new(_haContext, "light.attic_spot_middle_door");
    ///<summary>Office Lights</summary>
    public LightEntity OfficeLights => new(_haContext, "light.office_lights");
    ///<summary>Backyard Door Light</summary>
    public LightEntity BackyardDoorLight => new(_haContext, "light.backyard_door_light");
    ///<summary>Backyard Entrance Light</summary>
    public LightEntity BackyardEntranceLight => new(_haContext, "light.backyard_entrance_light");
    ///<summary>Backyard Fence String Lights</summary>
    public LightEntity BackyardFenceStringLights => new(_haContext, "light.backyard_fence_string_lights");
    ///<summary>Backyard Garage Light</summary>
    public LightEntity BackyardGarageLight => new(_haContext, "light.backyard_garage_light");
    ///<summary>Backyard Lights</summary>
    public LightEntity BackyardPergolaStringLights => new(_haContext, "light.backyard_pergola_string_lights");
    ///<summary>Backyard Porch Kerosene Light</summary>
    public LightEntity BackyardPorchStringLights => new(_haContext, "light.backyard_porch_string_lights");
}