using NetDaemon.HassModel;

namespace CodeCasa.AutoGenerated;

public partial class SensorEntities
{
    private readonly IHaContext _haContext;

    public SensorEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all sensor entities currently registered (at runtime) in Home Assistant as SensorEntity</summary>
    public IEnumerable<SensorEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.")).Select(e => new SensorEntity(e));
    /// <summary>Enumerates all non-numeric sensor entities currently registered (at runtime) in Home Assistant as SensorEntity</summary>
    public IEnumerable<SensorEntity> EnumerateAllNonNumeric() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.") && !(e.EntityState?.AttributesJson?.TryGetProperty("unit_of_measurement", out _) ?? false)).Select(e => new SensorEntity(e));
    /// <summary>Enumerates all numeric sensor entities currently registered (at runtime) in Home Assistant as NumericSensorEntity</summary>
    public IEnumerable<NumericSensorEntity> EnumerateAllNumeric() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.") && (e.EntityState?.AttributesJson?.TryGetProperty("unit_of_measurement", out _) ?? false)).Select(e => new NumericSensorEntity(e));

    ///<summary>Bathroom Motion Sensor Illuminance</summary>
    public NumericSensorEntity BathroomMotionSensorIlluminance => new(_haContext, "sensor.bathroom_motion_sensor_illuminance");

    ///<summary>Living Room Temperature</summary>
    public NumericSensorEntity LivingRoomTemperature => new(_haContext, "sensor.living_room_temperature");
    ///<summary>Meteorologisk Temperature</summary>
    public NumericSensorEntity MeteorologiskTemperature => new(_haContext, "sensor.meteorologisk_temperature");

    ///<summary>Kitchen speaker alarms</summary>
    public SensorEntity KitchenSpeakerAlarms => new(_haContext, "sensor.kitchen_speaker_alarms");
    ///<summary>Kitchen speaker timers</summary>
    public SensorEntity KitchenSpeakerTimers => new(_haContext, "sensor.kitchen_speaker_timers");
    ///<summary>Living Room speaker alarms</summary>
    public SensorEntity LivingRoomSpeakerAlarms => new(_haContext, "sensor.living_room_speaker_alarms");
    ///<summary>Living Room speaker timers</summary>
    public SensorEntity LivingRoomSpeakerTimers => new(_haContext, "sensor.living_room_speaker_timers");
    ///<summary>Office Motion Sensor Illuminance</summary>
    public NumericSensorEntity OfficeMotionSensorIlluminance => new(_haContext, "sensor.office_motion_sensor_illuminance");
    ///<summary>Office speaker alarms</summary>
    public SensorEntity OfficeSpeakerAlarms => new(_haContext, "sensor.office_speaker_alarms");
    ///<summary>Office speaker timers</summary>
    public SensorEntity OfficeSpeakerTimers => new(_haContext, "sensor.office_speaker_timers");
    ///<summary>Upstairs Hallway Attic Motion Sensor Illuminance</summary>
    public NumericSensorEntity UpstairsHallwayAtticMotionSensorIlluminance => new(_haContext, "sensor.upstairs_hallway_attic_motion_sensor_illuminance");
}