using CodeCasa.AutoGenerated;
using CodeCasa.Notifications.Phone.NetDaemon;
using NetDaemon.HassModel;

namespace CodeCasa.CustomEntities.Automation.Notifications.Phones;

public class JanePhoneNotifications(NotifyServices notificationServices, IHaContext haContext)
    : PhoneNotificationEntity(haContext, notificationServices.MobileAppIphoneVanJane);