using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.People;
using CodeCasa.CustomEntities.Automation.Sensors;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.AppModel;
using System.Drawing;
using System.Reactive.Concurrency;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;
using CodeCasa.Notifications.Lights;

namespace CodeCasa.Automations.Apps.Lights.OfficeLights;

[NetDaemonApp]
internal class OfficeLightsApp
{
    public OfficeLightsApp(
        LightPipelineFactory lightPipelineFactory,
        LightEntities lightEntities,
        LightNotificationManagerContext lightNotificationManager,
        OfficeMotionSensor officeMotionSensor,
        OfficeWallModuleSingleRocker officeWallModuleSingleRocker,
        OfficeDimmerSwitch officeDimmerSwitch,
        PeopleEntities people)
    {
        lightPipelineFactory
            .SetupLightPipeline(lightEntities.OfficeLights, builder =>
            {
                builder
                    .AddReactiveNode(rc =>
                    {
                        rc
                            //.AddCycle(officeDimmerSwitch.ScenePressed, LightScenes.Bright, LightScenes.Concentrate)
                            .AddToggle(officeDimmerSwitch.OnOffPressed, c =>
                            {
                                c
                                    .Add(LightParameters.Relax)
                                    .ForLight(lightEntities.OfficeLightColor1.EntityId, c1 =>
                                    {
                                        c1.Add(context => new ColorTransitionNode(
                                            context.ServiceProvider.GetRequiredService<IScheduler>(),
                                            TimeSpan.FromSeconds(3),
                                            Color.Red, Color.Blue, Color.LawnGreen));
                                    })
                                    .ForLight(lightEntities.OfficeLightColor2.EntityId, c2 =>
                                    {
                                        c2.Add(context => new ColorTransitionNode(
                                            context.ServiceProvider.GetRequiredService<IScheduler>(),
                                            TimeSpan.FromSeconds(3),
                                            Color.Cyan, Color.Yellow, Color.Magenta));
                                    });
                            });
                            //.AddToggle(officeDimmerSwitch.ScenePressed, c => c.Add<TestNode>())
                            //.AddToggle(officeDimmerSwitch.ScenePressed, c => c.Add(ctx => new TestNode(ctx, ctx.ServiceProvider.GetRequiredService<IScheduler>())))
                            //.AddToggle(officeDimmerSwitch.OnOffPressed, c => c.Add<TestNode>())
                        //.TurnOffWhen(people.OnLastPersonToAsleepOrAwayObservable().Where(b => b)
                        //    .Select(_ => Unit.Default));
                    });
                //.AddNode<AlarmNode>();
                //.SupportNotifications(lightNotificationManager);
            });
    }
}