using CodeCasa.AutoGenerated;
using CodeCasa.AutomationPipelines.Lights.Extensions;
using CodeCasa.AutomationPipelines.Lights.Pipeline;
using CodeCasa.CustomEntities.Automation.Sensors;
using CodeCasa.CustomEntities.Automation.Switches;
using CodeCasa.Lights;
using NetDaemon.AppModel;
using System.Reactive.Concurrency;
using CodeCasa.AutomationPipelines.Lights.NetDaemon.Extensions;

namespace CodeCasa.Automations.Apps.Lights.AtticLights
{
    [Focus]
    [NetDaemonApp]
    internal class AtticLightApp
    {
        public AtticLightApp(
            LightPipelineFactory lightPipelineFactory,
            LightEntities lightEntities,
            UpstairsHallwayAtticMotionSensor motionSensor,
            AtticWallSwitch atticWallSwitch,
            IScheduler scheduler)
        {
            lightPipelineFactory.SetupLightPipeline(lightEntities.AtticSpotMiddleDoor, b =>
            {
                b.EnableLogging("Attic Pipeline")
                    .When<UpstairsHallwayAtticMotionSensor>(LightParameters.Bright)
                .AddReactiveNode(c =>
                    c.AddToggle(atticWallSwitch, 
                        sp =>
                        sp.CreateAutoOffLightNode(LightParameters.Bright, TimeSpan.FromSeconds(60), motionSensor.Motion)));
            });
        }
    }
}
