using System.Reactive.Concurrency;
using CodeCasa.Abstractions;
using CodeCasa.AutoGenerated;
using CodeCasa.Automations.Nodes;
using CodeCasa.Lights;
using CodeCasa.Lights.NetDaemon;
using CodeCasa.NetDaemon.Extensions.Observables;
using CodeCasa.Notifications.Lights;
using Microsoft.Extensions.DependencyInjection;
using NetDaemon.AppModel;

namespace CodeCasa.Automations.Apps.Notifications;

[NetDaemonApp]
internal class AlarmLight
{
    public AlarmLight(
        IScheduler scheduler,
        LightEntities lightEntities,
        LightNotificationContext lightNotification)
    {
        lightEntities.BackyardPergolaStringLights.SubscribeOnOff(
            () => lightNotification.Notify<TestLight>("alarm", sp => new AlarmNode(sp.GetRequiredService<IScheduler>(), sp.GetRequiredService<NetDaemonLight>())),
            () => lightNotification.RemoveNotification("alarm"));
    }
}

public class TestLight : ILight
{
    public string Id { get; }
    public LightParameters GetParameters()
    {
        throw new NotImplementedException();
    }

    public void ApplyTransition(LightTransition transition)
    {
        throw new NotImplementedException();
    }

    public ILight[] GetChildren()
    {
        throw new NotImplementedException();
    }

    public IObservable<StateChange<ILight, LightParameters>> StateChanges()
    {
        throw new NotImplementedException();
    }

    public IObservable<StateChange<ILight, LightParameters>> StateChangesWithCurrent()
    {
        throw new NotImplementedException();
    }
}